# Generated by Django 2.1.7 on 2019-05-13 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=255)),
                ('music_name', models.CharField(max_length=255)),
                ('music_img', models.CharField(max_length=255)),
                ('music_author', models.CharField(max_length=255)),
                ('music_album', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MusicLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MusicStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=100)),
                ('list_title', models.CharField(max_length=500)),
                ('list_img', models.CharField(max_length=500)),
                ('list_tag', models.CharField(max_length=500)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.MusicLanguage')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.MusicStyle')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='music_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.SongList'),
        ),
    ]
