# Generated by Django 2.1.7 on 2019-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_id', models.CharField(max_length=100)),
                ('mv_name', models.CharField(max_length=500)),
                ('mv_author', models.CharField(max_length=100)),
                ('mv_desc', models.CharField(max_length=800)),
                ('mv_pic', models.CharField(max_length=500)),
                ('playCount', models.CharField(max_length=100)),
                ('publishTime', models.CharField(max_length=100)),
                ('mv_url_240', models.CharField(default='', max_length=800, null=True)),
                ('mv_url_480', models.CharField(default='', max_length=800, null=True)),
                ('mv_url_720', models.CharField(default='', max_length=800, null=True)),
                ('mv_url_1080', models.CharField(default='', max_length=800, null=True)),
            ],
        ),
    ]
