# Generated by Django 2.1.7 on 2019-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_mv'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
